name: Testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 5.3
          - 5.4
          - 5.5
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
        dependency-levels:
          - 'highest'
        experimental:
          - false
        include:
          - php-versions: 5.4
            dependency-levels: 'lowest'
            experimental: false
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validating PHP syntax
      run: find ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

    - name: Validate composer.json and composer.lock
      run: composer validate

      # Because PHPCS 3 requires PHP 5.4
    - run: composer require --dev -W squizlabs/php_codesniffer:^2.0 symfony/yaml:^2.0 phpdocumentor/reflection-docblock:^2.0
      if: matrix.php-versions == '5.3'

    - name: Install dependencies
      uses: ramsey/composer-install@v1
      with:
        dependency-versions: "${{ matrix.dependency-levels }}"
        composer-options: "--prefer-dist"

    - name: PhpUnit
      run: ./vendor/bin/phpunit

    - name: PHPCS
      run: ./vendor/bin/phpcs -s --report-source --runtime-set ignore_warnings_on_exit 1
      # Because PHPCS 2 does not have PSR-12 rule
      if: matrix.php-versions != '5.3'
